Repository aws/aws-sdk-pandas, pull requests merged in 2019-10, with the labels that each got.

#39 Normalize Athena names (tables and columns)
  awswrangler/athena.py
  awswrangler/glue.py
  awswrangler/pandas.py
  testing/test_awswrangler/test_pandas.py
Labels: enhancement

#40 Removing Pandas duplicated columns
  awswrangler/pandas.py
  testing/test_awswrangler/test_pandas.py
Labels: enhancement

#41 Improving exception info
  awswrangler/glue.py
  testing/test_awswrangler/test_pandas.py
Labels: enhancement

#42 Add Athena Workgroup
  awswrangler/athena.py
  awswrangler/session.py
  testing/test_awswrangler/test_athena.py
Labels: enhancement

#43 Normalizing partitions and casting columns names
  awswrangler/pandas.py
  testing/test_awswrangler/test_pandas.py
Labels: bug

#49 Fix pandas to redshift cast feature
  awswrangler/pandas.py
  testing/test_awswrangler/test_redshift.py
Labels: bug

#53 Log the names of duplicated columns and not boolean array
  awswrangler/pandas.py
Labels: enhancement

#54 GeoPandas limitation explained in the docs
  README.md
  building/build-docs.sh
  building/build-glue-egg.sh
  building/build-glue-wheel.sh
  building/build-image.sh
  building/build-lambda-layer.sh
  building/deploy-source.sh
  building/open-image.sh
  building/publish.sh
  docs/source/divingdeep.rst
  setup-dev-env.sh
  testing/build-image.sh
  testing/open-image.sh
  testing/run-tests.sh
Labels: documentation

#55 Add Athena.query()
  awswrangler/athena.py
  awswrangler/data_types.py
  awswrangler/s3.py
  testing/test_awswrangler/test_athena.py
Labels: enhancement
