Repository aws/aws-sdk-pandas, pull requests merged in 2020-12, with the labels that each got.

#466 Update contributing test setup
  CONTRIBUTING.md
  cloudformation/databases.yaml
  cloudformation/delete-base.sh
  cloudformation/delete-databases.sh
  cloudformation/security-group-databases-add-local-ip.sh
  cloudformation/security-group-databases-check.sh
Labels: documentation

#470 Add database/table create/delete function for Timestream.
  awswrangler/timestream.py
  docs/source/api.rst
  tests/conftest.py
  tests/test_timestream.py
  tutorials/026 - Amazon Timestream.ipynb
  tutorials/027 - Amazon Timestream 2.ipynb
Labels: feature

#477 Adding S3 path validation for Redshift COPY.
  awswrangler/redshift.py
  tests/test_redshift.py
  tutorials/008 - Redshift - Copy & Unload.ipynb
Labels: Minor Release, documentation, enhancement

#482 Fix nested struct append.
  awswrangler/_data_types.py
  tests/test_athena_parquet.py
Labels: bug

#485 Feature/copy creds
  awswrangler/_utils.py
  awswrangler/redshift.py
Labels: Minor Release, feature

#489 [feat] added raw s3 credential authentication for Redshift copy commands
  awswrangler/redshift.py
Labels: enhancement

#490 Add tests for the new redshift credentials approaches.
  awswrangler/redshift.py
  tests/test_redshift.py
Labels: enhancement
