Repository aws/aws-sdk-pandas, pull requests merged in 2020-07, with the labels that each got.

#311 setting dtype to decimal results in "StringArray requires a sequence of strings or pandas.NA" error
  awswrangler/_data_types.py
Labels: bug

#301 Adding configuration mechanism
  README.md
  awswrangler/__init__.py
  awswrangler/_config.py
  awswrangler/_utils.py
  awswrangler/athena/_read.py
  awswrangler/athena/_utils.py
  awswrangler/catalog.py
  awswrangler/exceptions.py
  tests/test_config.py
  tutorials/021 - Global Configurations.ipynb
Labels: feature request

#328 S3 read/write refactoring.
  README.md
  awswrangler/_data_types.py
  awswrangler/_utils.py
  awswrangler/athena/_read.py
  awswrangler/catalog.py
  awswrangler/cloudwatch.py
  awswrangler/db.py
  awswrangler/emr.py
  awswrangler/exceptions.py
  awswrangler/quicksight/_cancel.py
  awswrangler/quicksight/_create.py
  awswrangler/quicksight/_delete.py
  awswrangler/quicksight/_describe.py
  awswrangler/quicksight/_get_list.py
  awswrangler/quicksight/_utils.py
  awswrangler/s3/__init__.py
  awswrangler/s3/_copy.py
  awswrangler/s3/_delete.py
  awswrangler/s3/_describe.py
  awswrangler/s3/_list.py
  awswrangler/s3/_read.py
  awswrangler/s3/_read_concurrent.py
  awswrangler/s3/_read_parquet.py
  awswrangler/s3/_read_text.py
  awswrangler/s3/_wait.py
  awswrangler/s3/_write.py
  awswrangler/s3/_write_concurrent.py
  awswrangler/s3/_write_parquet.py
  awswrangler/s3/_write_text.py
  requirements-dev.txt
  requirements.txt
  tests/_utils.py
  tests/test_athena_parquet.py
  tests/test_cloudwatch.py
  tests/test_moto.py
  tests/test_s3.py
  tests/test_s3_parquet.py
  tests/test_s3_text.py
  tox.ini
Labels: Minor Release

#327 Support writing encrypted redshift copy manifest to S3
  awswrangler/db.py
Labels: enhancement

#331 F/athena query add metadata
  awswrangler/athena/_read.py
  awswrangler/athena/_utils.py
  tests/_utils.py
  tests/test_athena.py
  tests/test_athena_cache.py
Labels: Minor Release, feature request

#332 updated docs
  awswrangler/athena/_utils.py
Labels: Minor Release, documentation

#334 add show create table
  awswrangler/athena/__init__.py
  awswrangler/athena/_utils.py
  tests/test_athena.py
Labels: Minor Release, enhancement
