Repository aws/aws-sdk-pandas, pull requests merged in 2020-01, with the labels that each got.

#94 Adding glue catalog utilities
  awswrangler/glue.py
  awswrangler/pandas.py
  awswrangler/spark.py
  demo/getting_started.ipynb
  testing/test_awswrangler/test_glue.py
  testing/test_awswrangler/test_pandas.py
Labels: enhancement

#93 Aurora MySQL Load check the number of files loaded after commit
  awswrangler/aurora.py
  awswrangler/pandas.py
  testing/test_awswrangler/test_pandas.py
Labels: bug

#92 Improving Sagemaker module
  README.md
  awswrangler/exceptions.py
  awswrangler/sagemaker.py
  docs/source/examples.rst
  docs/source/index.rst
  testing/test_awswrangler/test_sagemaker.py
Labels: enhancement

#98 Adding Glue.get_connection()
  awswrangler/glue.py
  testing/parameters.properties
  testing/template.yaml
  testing/test_awswrangler/test_glue.py
Labels: WIP, enhancement

#96 Fixing sagemaker get_model() for xgboost
  awswrangler/sagemaker.py
  testing/test_awswrangler/test_sagemaker.py
Labels: bug

#103 Athena
  awswrangler/pandas.py
  testing/test_awswrangler/test_pandas.py
Labels: bug, enhancement

#104 Improving Aurora tests
  awswrangler/aurora.py
  testing/test_awswrangler/test_pandas.py
Labels: enhancement

#106 Inverting file format and file compression extensions (key prefix)
  awswrangler/pandas.py
  testing/test_awswrangler/test_pandas.py
Labels: enhancement

#108 Handling null values for Pandas.to_aurora() and eventual consistency for postgres load
  awswrangler/aurora.py
  awswrangler/pandas.py
  awswrangler/s3.py
  testing/test_awswrangler/test_pandas.py
Labels: bug

#115 Handling categorical partitions
  awswrangler/pandas.py
  testing/test_awswrangler/test_pandas.py
Labels: bug, enhancement

#116 Removing regular indexes from the compulsory Int64 cast
  awswrangler/pandas.py
  testing/test_awswrangler/test_pandas.py
Labels: bug, enhancement

#117 Add columns parameters to Pandas.to_aurora() and Pandas.to_csv()
  awswrangler/aurora.py
  awswrangler/data_types.py
  awswrangler/glue.py
  awswrangler/pandas.py
  requirements-dev.txt
  requirements.txt
  testing/test_awswrangler/test_pandas.py
Labels: WIP, enhancement

#119 Fixing bug to unload null values from Aurora
  awswrangler/pandas.py
  testing/test_awswrangler/test_pandas.py
Labels: bug

#120 Handling empty results for Pandas.read_sql_redshift()
  awswrangler/pandas.py
  awswrangler/redshift.py
  testing/test_awswrangler/test_pandas.py
  testing/test_awswrangler/test_redshift.py
Labels: bug

#124 Defaults serde in glue.csv_table_definition
  awswrangler/glue.py
Labels: bug, documentation

#126 Forward all pandas kwargs
  awswrangler/pandas.py
Labels: enhancement
