Repository aws/aws-sdk-pandas, pull requests merged in 2020-04, with the labels that each got.

#155 Use AWS Session Token when available to build a session
  awswrangler/session.py
Labels: Version 1.0.0, bug

#156 disable remove repeated underscores rule from _normalize_name as athena allows it
  awswrangler/athena.py
Labels: Version 1.0.0, WIP, bug

#157 disable normalize name to remove underscore as underscore is allowed in athena columnName
  awswrangler/athena.py
Labels: Version 1.0.0, bug

#164 Add categories argument for all read_parquet related functions
  awswrangler/athena.py
  awswrangler/db.py
  awswrangler/s3.py
  testing/test_awswrangler/_utils.py
  testing/test_awswrangler/test_data_lake.py
  testing/test_awswrangler/test_db.py
  tutorials/06 - Amazon Athena.ipynb
Labels: enhancement

#163 improving the column name sanitisation
  awswrangler/catalog.py
  awswrangler/s3.py
  testing/test_awswrangler/test_data_lake.py
Labels: enhancement

#162 Fixing athena queries for workgroups without encryption
  awswrangler/athena.py
  testing/test_awswrangler/test_data_lake.py
Labels: bug

#165 Add categories arg to athena.read_sql_table #160
  awswrangler/athena.py
  testing/test_awswrangler/test_data_lake.py
Labels: enhancement, feature request

#169 Revisiting the lambda layer building
  .github/workflows/static-checking.yml
  building/build-lambda-layers.sh
  building/lambda/Dockerfile
  building/lambda/build-apache-arrow.sh
  building/lambda/build-lambda-layer.sh
  building/lambda/build-layer.sh
  building/lambda/build-pyarrow.sh
  setup-dev-env.sh
Labels: enhancement

#168 added validate_schema parameter to read_parquet
  awswrangler/s3.py
  testing/test_awswrangler/test_data_lake.py
Labels: enhancement

#173 Add notes about the last release and also fix links in the docs #171
  README.md
  docs/source/api.rst
  docs/source/index.rst
  docs/source/install.rst
  docs/source/what.rst
Labels: bug

#174 Fix missing boto3_session argument #172
  awswrangler/s3.py
Labels: bug

#176 Add Dataset feature to s3.to_csv #141 #170
  .pylintrc
  awswrangler/_data_types.py
  awswrangler/catalog.py
  awswrangler/s3.py
  docs/source/api.rst
  testing/run-tests.sh
  testing/test_awswrangler/_utils.py
  testing/test_awswrangler/test_data_lake.py
  testing/test_awswrangler/test_db.py
Labels: Version 1.0.0, bug, enhancement, feature request

#177 Add csv decompression for s3.read_csv #175
  awswrangler/s3.py
  testing/test_awswrangler/test_data_lake.py
Labels: bug

#179 fixing read_csv missing session token and broken s3 path
  awswrangler/athena.py
Labels: bug

#180 Add first tests with moto #109
  requirements-dev.txt
  testing/test_awswrangler/test_moto.py
Labels: enhancement

#182 Fixing casting with char and varchar lengths
  awswrangler/_data_types.py
  testing/test_awswrangler/test_data_lake.py
Labels: bug

#183 add CSV tutorials #181
  README.md
  tutorials/11 - CSV Datasets.ipynb
  tutorials/12 - CSV Crawler.ipynb
Labels: documentation, question

#185 Adding a note about collisions for sanitize_dataframe_columns_names.
  awswrangler/catalog.py
Labels: documentation

#187 Add s3.copy_objects()
  README.md
  awswrangler/_utils.py
  awswrangler/athena.py
  awswrangler/db.py
  awswrangler/s3.py
  docs/source/api.rst
  testing/test_awswrangler/test_data_lake.py
  tutorials/13 - Merging Datasets on S3.ipynb
Labels: bug, enhancement

#189 Add append mode to create_*_table
  awswrangler/catalog.py
  testing/test_awswrangler/test_data_lake.py
Labels: enhancement

#194 Registering module's type annotations
  MANIFEST.in
  awswrangler/py.typed
  setup.py
Labels: enhancement

#196 Bumping version to 1.0.4
  README.md
  awswrangler/__metadata__.py
  testing/test_awswrangler/test_metadata.py
Labels: Version 1.0.4

#204 change _create_table (catalog.py) default behavior to do not remove table if exists
  awswrangler/catalog.py
  awswrangler/s3.py
Labels: Minor Release, WIP, enhancement

#208 Add support for Docker and custom classification on EMR
  awswrangler/__init__.py
  awswrangler/_utils.py
  awswrangler/athena.py
  awswrangler/emr.py
  awswrangler/s3.py
  docs/source/api.rst
  requirements-dev.txt
  testing/test_awswrangler/test_cloudwatch.py
  testing/test_awswrangler/test_data_lake.py
  testing/test_awswrangler/test_emr.py
  testing/test_awswrangler/test_moto.py
  tutorials/15 - EMR.ipynb
  tutorials/16 - EMR & Docker.ipynb
Labels: Minor Release, WIP, feature request

#209 Add chunked=INTEGER option to ensure batch number of rows
  awswrangler/athena.py
  awswrangler/db.py
  awswrangler/s3.py
  testing/test_awswrangler/test_data_lake.py
Labels: Minor Release, WIP, feature request

#210 Pytorch Module
  .github/workflows/static-checking.yml
  .pylintrc
  README.md
  awswrangler/__init__.py
  awswrangler/_data_types.py
  awswrangler/athena.py
  awswrangler/catalog.py
  awswrangler/cloudwatch.py
  awswrangler/db.py
  awswrangler/emr.py
  awswrangler/s3.py
  awswrangler/torch.py
  building/build-docs.sh
  docs/source/api.rst
  requirements-dev.txt
  requirements-torch.txt
  setup-dev-env.sh
  setup.py
  testing/run-validations.sh
  testing/test_awswrangler/test_data_lake.py
  testing/test_awswrangler/test_torch.py
  tox.ini
  tutorials/14 - PyTorch.ipynb
Labels: Minor Release, WIP

#212 Revisiting Athena encryption and workgroup
  awswrangler/athena.py
  awswrangler/emr.py
  testing/test_awswrangler/test_data_lake.py
  testing/test_awswrangler/test_torch.py
  tox.ini
Labels: Minor Release, enhancement

#214 Add kms_key_id, max_file_size and region to Redshift Unload
  awswrangler/_data_types.py
  awswrangler/db.py
  awswrangler/s3.py
  testing/cloudformation.yaml
  testing/test_awswrangler/test_db.py
  tox.ini
Labels: Minor Release, WIP, feature request
