Repository aws/aws-sdk-pandas, pull requests merged in 2020-05, with the labels that each got.

#219 Add support for query UUID columns on PostgreSQL and full NULL columns for all databases.
  testing/test_awswrangler/test_db.py
Labels: Minor Release, bug

#220 Add support to write nested types (array and struct).
  .gitignore
  awswrangler/_data_types.py
  awswrangler/db.py
  testing/test_awswrangler/test_data_lake.py
Labels: Minor Release, enhancement

#221 Add keep_files and ctas_temp_table_name to wr.athena.read_*().
  awswrangler/athena.py
  awswrangler/torch.py
  testing/test_awswrangler/test_data_lake.py
Labels: Minor Release, enhancement

#228 Bumping version to 1.1.2
  README.md
  awswrangler/__metadata__.py
  awswrangler/_data_types.py
  awswrangler/_utils.py
  awswrangler/catalog.py
  awswrangler/db.py
  awswrangler/s3.py
  docs/source/api.rst
  requirements-dev.txt
  requirements.txt
  testing/test_awswrangler/test_data_lake.py
  testing/test_awswrangler/test_metadata.py
  tutorials/14 - PyTorch.ipynb
Labels: Micro Release

#238 raise Exception if delete_objects failed
  awswrangler/s3.py
Labels: Minor Release, enhancement

#243 Schema Evolution
  awswrangler/_data_types.py
  awswrangler/catalog.py
  awswrangler/s3.py
  docs/source/api.rst
  requirements-dev.txt
  testing/test_awswrangler/test_data_lake.py
  tox.ini
Labels: feature request

#244 Fix typos in install doc
  docs/source/install.rst
Labels: documentation

#245 _utils: Make sure boto3's default session is used
  awswrangler/_utils.py
Labels: enhancement

#246 Add tests to the new default session.
  awswrangler/_utils.py
  testing/test_awswrangler/test_session.py
  tutorials/02 - Sessions.ipynb
Labels: enhancement

#248 Add test raise s3 exception
  testing/test_awswrangler/test_moto.py
Labels: enhancement

#253 Fix get_region_from_subnet bug
  awswrangler/_utils.py
  awswrangler/emr.py
Labels: Micro Release, bug

#255 Add test cases for get bukcet, object exists, list dirs and list file…
  testing/test_awswrangler/test_moto.py
Labels: enhancement

#257 refactor naming
  awswrangler/s3.py
Labels: enhancement

#258 add tests for describe objects
  testing/test_awswrangler/test_moto.py
Labels: enhancement

#262 Refactor naming
  awswrangler/s3.py
Labels: enhancement

#260 add test cases
  testing/test_awswrangler/test_moto.py
Labels: enhancement

#264 Fix bug to write partitions in reverse order.
  awswrangler/_data_types.py
  testing/test_awswrangler/test_data_lake.py
Labels: Minor Release, bug

#266 Releasing version 1.3.0
  .pylintrc
  README.md
  awswrangler/__metadata__.py
  awswrangler/_data_types.py
  awswrangler/_utils.py
  awswrangler/catalog.py
  awswrangler/emr.py
  awswrangler/s3.py
  requirements-dev.txt
  requirements.sh
  requirements.txt
  testing/cloudformation.sh
  testing/cloudformation.yaml
  testing/test_awswrangler/test_athena_projection.py
  testing/test_awswrangler/test_data_lake.py
  testing/test_awswrangler/test_metadata.py
  testing/test_awswrangler/test_moto.py
  tutorials/17 - Partition Projection.ipynb
Labels: Minor Release
