Repository aws/aws-sdk-pandas, pull requests merged in 2020-02, with the labels that each got.

#127 Add support to Redshift Spectrum on Glue metadata
  awswrangler/glue.py
  awswrangler/pandas.py
  awswrangler/redshift.py
  testing/deploy-cloudformation.sh
  testing/parameters.properties
  testing/template.yaml
  testing/test_awswrangler/test_aurora.py
  testing/test_awswrangler/test_pandas.py
  testing/test_awswrangler/test_redshift.py
Labels: enhancement

#128 Bumping Pandas version to 1.0.0
  awswrangler/data_types.py
  awswrangler/glue.py
  requirements-dev.txt
  requirements.txt
  testing/test_awswrangler/test_pandas.py
  testing/test_awswrangler/test_redshift.py
Labels: enhancement

#129 Fix read_csv for compressed files
  awswrangler/pandas.py
  data_samples/small.csv.gz
  testing/test_awswrangler/test_pandas.py
Labels: enhancement

#130 Add support for EMR consistent view
  awswrangler/__init__.py
  awswrangler/emr.py
  awswrangler/session.py
  requirements-dev.txt
  testing/test_awswrangler/test_emr.py
Labels: enhancement

#131 Add Pandas.read_fwf(), Pandas.read_fwf_list() and Pandas.read_fwf_pre…
  awswrangler/pandas.py
  awswrangler/session.py
  data_samples/fwf_nano.txt
  data_samples/fwf_nano.txt.zip
  testing/test_awswrangler/test_pandas.py
Labels: enhancement

#136 Making test_head_object_with_retry public again
  awswrangler/pandas.py
  awswrangler/s3.py
  testing/build-image.sh
  testing/deploy-cloudformation.sh
  testing/start-jupyter.sh
  testing/test_awswrangler/test_s3.py
Labels: bug

#137 Adding test for sequential overwrites
  testing/test_awswrangler/test_pandas.py
Labels: question

#138 Now Pandas.read_parquet() will return Int64 for integers with null va…
  awswrangler/data_types.py
  awswrangler/pandas.py
  awswrangler/redshift.py
  testing/test_awswrangler/test_pandas.py
  testing/test_awswrangler/test_redshift.py
Labels: bug

#139 Add filename and header arguments for Pandas.to_csv().
  awswrangler/pandas.py
  testing/test_awswrangler/test_pandas.py
Labels: enhancement
