Repository aws/aws-sdk-pandas, pull requests merged in 2021-02, with the labels that each got.

#535 Add botocore Config to wr.config
  awswrangler/_config.py
  awswrangler/_utils.py
  awswrangler/timestream.py
  tests/test_config.py
  tutorials/021 - Global Configurations.ipynb
Labels: enhancement

#519 Added Python versions 3.7 and 3.8 for static-checking
  .github/workflows/static-checking.yml
Labels: enhancement

#541 Adding files with the common errors and the fixes
  CONTRIBUTING.md
  CONTRIBUTING_COMMON_ERRORS.md
Labels: documentation

#550 Minor Fix documentation for wr.redshift.unload
  awswrangler/redshift.py
Labels: documentation

#565 timezone should be applied before index is set
  awswrangler/s3/_read_parquet.py
Labels: bug

#568 Add ExpectedBucketOwner as botocore kwarg
  awswrangler/athena/_read.py
  awswrangler/athena/_utils.py
  awswrangler/redshift.py
  awswrangler/s3/_copy.py
  awswrangler/s3/_delete.py
  awswrangler/s3/_describe.py
  awswrangler/s3/_fs.py
  awswrangler/s3/_list.py
  awswrangler/s3/_write_excel.py
  awswrangler/s3/_write_parquet.py
  awswrangler/s3/_write_text.py
  awswrangler/sqlserver.py
Labels: enhancement

#560 Feature: Write to Glue Governed Tables
  CONTRIBUTING.md
  awswrangler/__init__.py
  awswrangler/_config.py
  awswrangler/_utils.py
  awswrangler/athena/_read.py
  awswrangler/catalog/_create.py
  awswrangler/catalog/_definitions.py
  awswrangler/lakeformation/__init__.py
  awswrangler/lakeformation/_read.py
  awswrangler/lakeformation/_utils.py
  awswrangler/s3/_write.py
  awswrangler/s3/_write_dataset.py
  awswrangler/s3/_write_parquet.py
  awswrangler/s3/_write_text.py
  cloudformation/base.yaml
  tests/_utils.py
  tests/conftest.py
  tests/test__routines.py
  tests/test_lakeformation.py
  tutorials/029 - Lake Formation Governed Tables.ipynb
Labels: WIP, feature

#572 Generate html doc for notebooks
  .readthedocs.yml
  awswrangler/_config.py
  awswrangler/athena/_read.py
  awswrangler/s3/_read_parquet.py
  awswrangler/s3/_read_text.py
  awswrangler/s3/_write_excel.py
  awswrangler/s3/_write_parquet.py
  awswrangler/s3/_write_text.py
  docs/environment.yml
  docs/source/_ext/copy_tutorials.py
  docs/source/_static/css/max_width.css
  docs/source/conf.py
  docs/source/index.rst
  docs/source/tutorials.rst
  docs/source/tutorials/.gitignore
  requirements-dev.txt
  requirements-docs.txt
  tutorials/003 - Amazon S3.ipynb
Labels: documentation

#574 Bump2version setup
  .bumpversion.cfg
  CONTRIBUTING.md
  requirements-dev.txt
Labels: documentation
