Repository aws/aws-sdk-pandas, pull requests merged in 2021-05, with the labels that each got.

#667 Redshift serializable isolation
  awswrangler/redshift.py
  tests/test_redshift.py
Labels: Minor Release, enhancement

#673 Add serde parameters to csv table creation
  awswrangler/catalog/_create.py
  awswrangler/catalog/_definitions.py
  awswrangler/s3/_write_text.py
  tests/test_athena_csv.py
Labels: Minor Release, Ready to release, enhancement

#664 Pass SSL properties from Glue Connection to MySQL
  awswrangler/_databases.py
  awswrangler/mysql.py
  cloudformation/databases.yaml
  tests/test_mysql.py
Labels: enhancement

#693 [skip ci] - Testing skipping ci
  .github/dependabot.yml
  CONTRIBUTING.md
  pyproject.toml
  requirements-dev.txt
  setup.cfg
Labels: enhancement

#718 Adding flag to skip Redshift transaction commit
  awswrangler/redshift.py
  tests/test_redshift.py
Labels: enhancement
