Repository aws/aws-sdk-pandas, pull requests merged in 2021-06, with the labels that each got.

#729 Enable prefix in output S3 files for unload_to_files
  awswrangler/redshift.py
  tests/test_redshift.py
Labels: enhancement

#706 Add CDK test infra
  .github/workflows/static-checking.yml
  .gitignore
  CONTRIBUTING.md
  cloudformation/base.yaml
  cloudformation/databases.yaml
  cloudformation/delete-base.sh
  cloudformation/delete-databases.sh
  cloudformation/deploy-base.sh
  cloudformation/deploy-databases.sh
  requirements-dev.txt
  test_infra/app.py
  test_infra/cdk.json
  test_infra/requirements.txt
  test_infra/scripts/delete-base.sh
  test_infra/scripts/delete-databases.sh
  test_infra/scripts/deploy-base.sh
  test_infra/scripts/deploy-databases.sh
  test_infra/scripts/security-group-databases-add-local-ip.sh
  test_infra/scripts/security-group-databases-check.sh
  test_infra/source.bat
  test_infra/stacks/__init__.py
  test_infra/stacks/base_stack.py
  test_infra/stacks/databases_stack.py
  tests/conftest.py
  tests/test_catalog.py
Labels: enhancement

#738 Wait for Athena bucket exists
  awswrangler/athena/_utils.py
Labels: Minor Release, Ready to release, enhancement

#742 Removing explicit Excel engine configuration
  awswrangler/s3/_read_excel.py
  awswrangler/s3/_write_excel.py
  tests/test_s3_excel.py
Labels: Minor Release, bug

#722 S3 Select
  awswrangler/s3/__init__.py
  awswrangler/s3/_select.py
  tests/test_s3_select.py
Labels: feature

#748 Adding S3 Select tutorial and small fixes
  .github/workflows/static-checking.yml
  README.md
  requirements-dev.txt
  tests/test_athena_parquet.py
  tutorials/029 - S3 Select.ipynb
  validate.sh
Labels: documentation

#761 Minor - Adding unload format to unload_files
  awswrangler/redshift.py
  tests/test_redshift.py
Labels: enhancement

#779 Safe get on table columns comments
  awswrangler/catalog/_get.py
  tests/test_athena.py
Labels: bug
