Repository aws/aws-sdk-pandas, pull requests merged in 2021-04, with the labels that each got.

#612 Fixing nested struct bug in athena2pyarrow method
  awswrangler/_data_types.py
Labels: Minor Release, bug

#631 Read parquet table chunked
  awswrangler/s3/_read_parquet.py
Labels: Minor Release, bug

#632 Add postgres as accepted connection kind
  awswrangler/postgresql.py
Labels: Minor Release, enhancement

#622 Prepend prefix to to_parquet created files
  awswrangler/s3/_write_dataset.py
  awswrangler/s3/_write_parquet.py
  awswrangler/s3/_write_text.py
  tests/conftest.py
  tests/test_s3_parquet.py
  tests/test_s3_text.py
Labels: Minor Release, enhancement

#645 Add exist_ok flag to create_database
  awswrangler/catalog/_create.py
  awswrangler/exceptions.py
  tests/conftest.py
  tests/test_athena.py
  tests/test_catalog.py
Labels: Minor Release, enhancement

#646 Add column name to unsupported pyarrow type exception
  awswrangler/_data_types.py
Labels: Minor Release, Ready to release, enhancement

#653 Enable parallel s3 downloads
  awswrangler/_utils.py
  awswrangler/s3/_fs.py
  awswrangler/s3/_read.py
  awswrangler/s3/_read_excel.py
  awswrangler/s3/_read_parquet.py
  awswrangler/s3/_read_text.py
  tests/test_s3_excel.py
  tests/test_s3_parquet.py
  tests/test_s3_text.py
  tests/test_utils.py
Labels: Minor Release, enhancement

#657 Fix get_query_column_types to return the correct format for decimal d…
  awswrangler/athena/_utils.py
  tests/test_athena.py
Labels: Minor Release, Ready to release, enhancement

#661 Make use of pyarrow iter_batches
  awswrangler/s3/_read_parquet.py
Labels: Minor Release, Ready to release, enhancement

#662 Add dtypes for empty ctas athena queries
  awswrangler/athena/_read.py
  tests/test_athena.py
  tests/test_athena_parquet.py
Labels: Minor Release, bug
