Repository aws/aws-sdk-pandas, pull requests merged in 2021-01, with the labels that each got.

#499 Add params to athena sql
  awswrangler/athena/_read.py
  tests/test_athena.py
Labels: enhancement

#500 Hotfix: Fix packages in setup
  setup.py
Labels: bug

#494 Adding functionality to send Chime notifications
  README.md
  awswrangler/__init__.py
  awswrangler/chime.py
  docs/source/api.rst
  tests/test_chime.py
Labels: feature

#491 Add support for S3 Access Points (#393)
  awswrangler/_utils.py
Labels: feature

#504 Add local metadata caching
  awswrangler/_config.py
  awswrangler/athena/_read.py
  awswrangler/athena/_utils.py
  tests/test_athena_cache.py
  tests/test_config.py
  tutorials/021 - Global Configurations.ipynb
Labels: feature

#508 Add Excel support and some refactoring.
  README.md
  awswrangler/__metadata__.py
  awswrangler/s3/__init__.py
  awswrangler/s3/_fs.py
  awswrangler/s3/_read_excel.py
  awswrangler/s3/_write_excel.py
  awswrangler/s3/_write_text.py
  docs/source/api.rst
  requirements-dev.txt
  requirements-docs.txt
  requirements.txt
  tests/test_fs.py
  tests/test_metadata.py
  tests/test_s3_excel.py
  tests/test_sqlserver.py
  tox.ini
  tutorials/003 - Amazon S3.ipynb
Labels: feature

#513 Fix broken hyperlink in README
  README.md
Labels: documentation

#516 Include bucketing for s3 datasets writing
  awswrangler/catalog/_add.py
  awswrangler/catalog/_create.py
  awswrangler/catalog/_definitions.py
  awswrangler/s3/_write.py
  awswrangler/s3/_write_dataset.py
  awswrangler/s3/_write_parquet.py
  awswrangler/s3/_write_text.py
  tests/test_athena.py
Labels: feature

#520 Remove Profanity in Redshift Docstrings
  awswrangler/redshift.py
Labels: documentation

#510 New functionality to allow merge upsert on existing table.
  awswrangler/s3/_merge_upsert_table.py
  docs/source/api.rst
  tests/test_s3_merge_upsert.py
Labels: feature

#512 Upload/download files to/from S3
  awswrangler/s3/__init__.py
  awswrangler/s3/_download.py
  awswrangler/s3/_upload.py
  docs/source/api.rst
  tests/test_moto.py
  tutorials/003 - Amazon S3.ipynb
Labels: feature

#527 Return DataFrame with unique index for Athena CTAS queries
  awswrangler/athena/_read.py
  awswrangler/s3/_read_parquet.py
Labels: bug

#539 Update feature issue template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation
