Repository aws/aws-sdk-pandas, pull requests merged in 2021-03, with the labels that each got.

#581 Making datetime timezone aware in CW module and adding security token in Redshift
  awswrangler/cloudwatch.py
  tests/test_redshift.py
Labels: enhancement

#587 Bumping pg8000 version to 1.19
  requirements.txt
Labels: enhancement

#583 Add flag for using column names in to_sql
  awswrangler/mysql.py
  awswrangler/postgresql.py
  awswrangler/redshift.py
  awswrangler/sqlserver.py
  tests/test_mysql.py
  tests/test_postgresql.py
  tests/test_redshift.py
  tests/test_sqlserver.py
Labels: enhancement

#595 Adding ctas_database_name argument
  awswrangler/athena/_read.py
  tests/conftest.py
  tests/test_athena.py
Labels: Major Release, enhancement

#590 Feature: Add flag to disable pyarrow DataTypes conversion
  awswrangler/s3/_read_parquet.py
  tests/test_s3_parquet.py
Labels: Major Release, enhancement

#598 Major - Make path argument in wr.s3.to functions optional
  awswrangler/s3/_write.py
  awswrangler/s3/_write_parquet.py
  awswrangler/s3/_write_text.py
  tests/test__routines.py
  tests/test_athena_csv.py
  tests/test_s3.py
Labels: Minor Release, enhancement

#600 Insert multiple rows at once in to_sql
  awswrangler/_config.py
  awswrangler/_databases.py
  awswrangler/mysql.py
  awswrangler/postgresql.py
  awswrangler/redshift.py
  awswrangler/sqlserver.py
  tests/test_config.py
  tests/test_mysql.py
  tests/test_postgresql.py
  tests/test_redshift.py
  tests/test_sqlserver.py
Labels: Minor Release, enhancement, feature

#614 Raising exception when quality check fails
  awswrangler/exceptions.py
  awswrangler/s3/_merge_upsert_table.py
  tests/test_s3_merge_upsert.py
Labels: Minor Release, enhancement

#613 Mysql upsert
  awswrangler/mysql.py
  tests/test_mysql.py
Labels: Minor Release, enhancement
