Repository aws/aws-sdk-pandas, pull requests merged in 2022-06, with the labels that each got.

#1372 Revert "[skip ci] pip(deps-dev): Bump mypy from 0.910 to 0.960 (#1363)"
  poetry.lock
  pyproject.toml
Labels: bug

#1369 Enable s3.to_parquet to recieve "zstd" compression type
  awswrangler/s3/_write.py
  awswrangler/s3/_write_parquet.py
  tests/test_s3_parquet.py
Labels: enhancement

#1380 Updating mypy -> 0.960
  awswrangler/s3/_read.py
  poetry.lock
  pyproject.toml
Labels: dependencies

#1370 read_parquet Does Not Throw Error for Missing Column
  awswrangler/s3/_read.py
  awswrangler/s3/_read_parquet.py
Labels: enhancement
