Repository aws/aws-sdk-pandas, pull requests merged in 2022-09, with the labels that each got.

#1567 Distributed S3 read text
  awswrangler/distributed/_utils.py
  awswrangler/s3/_read_parquet.py
  awswrangler/s3/_read_text.py
  test_infra/stacks/base_stack.py
  tests/load/test_s3.py
  tests/unit/test_moto.py
  tests/unit/test_s3_text.py
  tests/unit/test_s3_text_compressed.py
Labels: Major Release

#1579 feature: Add support for upserting to an empty Glue table
  awswrangler/s3/_merge_upsert_table.py
  tests/test_s3_merge_upsert.py
Labels: bug

#1578 update wheel library as it is causing issues in some environments
  poetry.lock
  pyproject.toml
Labels: bug, dependencies

#1539 Distribute s3 wait_objects
  awswrangler/_threading.py
  awswrangler/distributed/_pool.py
  awswrangler/s3/_wait.py
  tests/load/test_s3.py
  tests/unit/test_s3.py
Labels: enhancement, Major Release

#1584 Tutorials Updating S3 Paths for Bucket `noaa-ghcn-pds`
  tutorials/006 - Amazon Athena.ipynb
  tutorials/008 - Redshift - Copy & Unload.ipynb
  tutorials/010 - Parquet Crawler.ipynb
  tutorials/019 - Athena Cache.ipynb
  tutorials/022 - Writing Partitions Concurrently.ipynb
Labels: documentation

#1586 XFail for QuickSight Test
  tests/test_quicksight.py
Labels: bug

#1581 Cast Athena array, map & struct types to pandas object
  awswrangler/_data_types.py
  awswrangler/athena/_utils.py
  tests/test_athena.py
Labels: Minor Release

#1583 Ray Load Tests CDK Stack and Instructions for Load Testing
  CONTRIBUTING.md
  test_infra/app.py
  test_infra/stacks/ray_stack.py
  tutorials/006 - Amazon Athena.ipynb
  tutorials/008 - Redshift - Copy & Unload.ipynb
  tutorials/010 - Parquet Crawler.ipynb
  tutorials/019 - Athena Cache.ipynb
  tutorials/022 - Writing Partitions Concurrently.ipynb
Labels: documentation

#1587 Fix: S3 read text with version ID was not working
  awswrangler/s3/_read_text.py
  tests/unit/test_s3_text.py
Labels: bug

#1588 Redshift Serverless test infrastructure
  test_infra/app.py
  test_infra/poetry.lock
  test_infra/pyproject.toml
  test_infra/stacks/base_stack.py
  test_infra/stacks/databases_stack.py
Labels: dependencies

#1605 (enhancement): Remove unnecessary LF permissions from tests infra
  CONTRIBUTING_COMMON_ERRORS.md
  test_infra/stacks/databases_stack.py
Labels: enhancement, documentation, continuous integration

#1606 update moto library and fix deprecation warnings
  poetry.lock
  pyproject.toml
  tests/test_moto.py
  tox.ini
Labels: dependencies

#1614 (docs) Fix NavBar to prevent overflow of search bar
  docs/source/about.rst
  docs/source/conf.py
  docs/source/index.rst
Labels: documentation

#1616 Tutorial: Run SDK for pandas job on ray cluster.
  README.md
  tutorials/034 - Distributing Calls on Ray Remote Cluster.ipynb
Labels: documentation

#1634 (enhancement): Add unload_approach to athena.read_sql_table
  awswrangler/athena/_read.py
  tests/test_athena_parquet.py
Labels: enhancement

#1627 feat: Pass additional partition projection params to wr.s3.to_parquet & cat…
  awswrangler/catalog/_create.py
  awswrangler/s3/_write_parquet.py
  awswrangler/s3/_write_text.py
Labels: feature, Minor Release

#1623 Ray Logging
  awswrangler/_config.py
  awswrangler/distributed/__init__.py
  awswrangler/distributed/_distributed.py
  awswrangler/distributed/_distributed.pyi
  awswrangler/lakeformation/_read.py
  awswrangler/s3/_delete.py
  awswrangler/s3/_read_parquet.py
  awswrangler/s3/_select.py
  awswrangler/s3/_wait.py
Labels: feature

#1636 Update install page in docs with screenshot of new managed layer name
  docs/source/_static/aws_lambda_managed_layer.png
  docs/source/install.rst
Labels: documentation

#1638 Consistency in param naming Athena
  awswrangler/athena/_read.py
  docs/source/_static/aws_lambda_managed_layer.png
  docs/source/install.rst
  tests/unit/test_athena.py
Labels: enhancement, breaking change
