Repository aws/aws-sdk-pandas, pull requests merged in 2022-08, with the labels that each got.

#1512 Updating CONTRIBUTING.md and CONTRIBUTING_COMMON_ERRORS.md
  CONTRIBUTING.md
  CONTRIBUTING_COMMON_ERRORS.md
Labels: documentation

#1474 Distributed s3 delete objects
  awswrangler/s3/_delete.py
  load_tests/_utils.py
  load_tests/conftest.py
  load_tests/test_s3.py
  load_tests/test_s3_select.py
Labels: enhancement

#1515 Support Data Wrangler
  README.md
Labels: documentation

#1517 bug: s3 delete tests failing in distributed codebase
  awswrangler/s3/_delete.py
  tests/test_s3.py
Labels: bug

#1514 Add generate_create_query to Athena for generating tables' and views' DDL query
  awswrangler/athena/__init__.py
  awswrangler/athena/_utils.py
  tests/test_athena.py
Labels: feature, Minor Release

#1513 (feat): Refactor to distribute s3.read_parquet
  awswrangler/_arrow.py
  awswrangler/_utils.py
  awswrangler/athena/_read.py
  awswrangler/distributed/_utils.py
  awswrangler/distributed/datasources/__init__.py
  awswrangler/distributed/datasources/parquet_datasource.py
  awswrangler/lakeformation/_read.py
  awswrangler/redshift.py
  awswrangler/s3/_read.py
  awswrangler/s3/_read_parquet.py
  awswrangler/s3/_select.py
  load_tests/test_s3.py
  tests/test_athena.py
  tests/test_athena_parquet.py
  tests/test_redshift.py
  tests/test_s3_parquet.py
  tests/test_s3_select.py
Labels: Major Release, feature

#1525 Consolidate unit and load tests
  .bumpversion.cfg
  .github/workflows/minimal-tests.yml
  CONTRIBUTING.md
  load_tests/_utils.py
  load_tests/conftest.py
  tests/_utils.py
  tests/load/__init__.py
  tests/load/test_s3.py
  tests/unit/__init__.py
  tests/unit/test_athena.py
  tests/unit/test_athena_cache.py
  tests/unit/test_athena_csv.py
  tests/unit/test_athena_parquet.py
  tests/unit/test_athena_projection.py
  tests/unit/test_catalog.py
  tests/unit/test_chime.py
  tests/unit/test_cloudwatch.py
  tests/unit/test_config.py
  tests/unit/test_data_api.py
  tests/unit/test_emr.py
  tests/unit/test_fs.py
  tests/unit/test_glue.py
  tests/unit/test_lakeformation.py
  tests/unit/test_metadata.py
  tests/unit/test_moto.py
  tests/unit/test_mysql.py
  tests/unit/test_neptune.py
  tests/unit/test_neptune_parsing.py
  tests/unit/test_opensearch.py
  tests/unit/test_oracle.py
  tests/unit/test_postgresql.py
  tests/unit/test_quicksight.py
  tests/unit/test_redshift.py
  tests/unit/test_routines.py
  tests/unit/test_s3.py
  tests/unit/test_s3_excel.py
  tests/unit/test_s3_merge_upsert.py
  tests/unit/test_s3_parquet.py
  tests/unit/test_s3_select.py
  tests/unit/test_s3_text.py
  tests/unit/test_s3_text_compressed.py
  tests/unit/test_session.py
  tests/unit/test_sqlserver.py
  tests/unit/test_timestream.py
  tests/unit/test_utils.py
  tox.ini
Labels: Major Release

#1416 Extended Athena Formatter (init)
  awswrangler/athena/_formatter.py
  awswrangler/athena/_read.py
  tests/unit/test_athena.py
  tests/unit/test_query_params_formatter.py
Labels: enhancement, Major Release

#1529 Check for pair of brackets in query preparation for Athena cache
  awswrangler/athena/_cache.py
Labels: bug, Minor Release

#1535 refact: Breaking Change - Modify named params style in Athena formatter
  awswrangler/athena/_read.py
  awswrangler/athena/_utils.py
  awswrangler/lakeformation/_read.py
  tests/unit/test_athena.py
  tests/unit/test_athena_params_formatter.py
  tests/unit/test_athena_parquet.py
Labels: enhancement, Major Release

#1543 Fix query parameter replacement replacing partial parameter names
  awswrangler/athena/_read.py
  tests/unit/test_athena.py
Labels: bug
