Repository aws/aws-sdk-pandas, pull requests merged in 2022-11, with the labels that each got.

#1735 Bug: Fixing index column validation in `s3.read.parquet()` validate schema
  awswrangler/s3/_read_parquet.py
  tests/test_s3_parquet.py
Labels: bug

#1741 (feat) Make tqdm progress reporting opt-in
  poetry.lock
  pyproject.toml
Labels: feature

#1744 (feat): Distribute describe_objects S3 method
  awswrangler/distributed/ray/_register.py
  awswrangler/s3/_describe.py
  awswrangler/s3/_read.py
Labels: feature

#1757 Bug: Replace extra_registries with extra_public_registries
  awswrangler/emr.py
Labels: bug

#1770 (docs) add distributed / ray api docs
  docs/source/api.rst
Labels: documentation

#1779 (fix) Allow read partitions with extra = in the value
  awswrangler/s3/_read.py
Labels: bug

#1780 (feat) s3 select - add retries
  awswrangler/_utils.py
  awswrangler/exceptions.py
  awswrangler/s3/_select.py
Labels: feature

#1785 Add describe_log_streams and filter_log_events to the CloudWatch module
  awswrangler/cloudwatch.py
  docs/source/api.rst
  tests/test_cloudwatch.py
Labels: feature

#1813 (deps) upgrade mypy -> `0.991`
  poetry.lock
  pyproject.toml
Labels: dependencies

#1818 Add auto termination policy to EMR
  awswrangler/emr.py
Labels: enhancement
