Repository aws/aws-sdk-pandas, pull requests merged in 2022-07, with the labels that each got.

#1407 Fixed ISSUE-1406
  awswrangler/neptune/client.py
  awswrangler/neptune/neptune.py
  tests/test_neptune.py
  tutorials/033 - Amazon Neptune.ipynb
Labels: bug, enhancement

#1433 Remove boto3_session reference from athena test and opensearch utils module
  awswrangler/opensearch/_utils.py
  tests/_utils.py
  tests/test_athena.py
Labels: bug

#1467 (enhancement): Enable passing kwargs to redshift_connector.connect
  awswrangler/redshift.py
  tests/test_redshift.py
Labels: enhancement, Minor Release

#1466 (Ci) Bug fix with mypy check | adding stub file
  awswrangler/distributed/_distributed.pyi
Labels: bug

#1464 Adding subdir for Distributed Wrangler Load Tests
  load_tests/__init__.py
  load_tests/test_s3_select.py
Labels: enhancement

#1481 Enable new CI pipeline for standard & distributed tests
  awswrangler/distributed/_distributed.py
  pyproject.toml
  tests/test_lakeformation.py
  tests/test_s3_select.py
Labels: continuous integration
