Repository aws/aws-sdk-pandas, pull requests merged in 2022-12, with the labels that each got.

#1821 timestream.query: add QueryId and NextToken to df attributes
  awswrangler/timestream.py
  tests/test_timestream.py
Labels: feature

#1827 `wr.quicksight.create_athena_dataset()`: Changing `sql_name` to optional variable with uuid
  awswrangler/quicksight/_create.py
Labels: enhancement, breaking change

#1819 add support for boto3 kwargs to timestream.create_table
  awswrangler/timestream.py
  tests/test_timestream.py
Labels: feature

#1824 Fix/issue 1571 dynamodb execute statement
  awswrangler/dynamodb/__init__.py
  awswrangler/dynamodb/_read.py
  awswrangler/dynamodb/_utils.py
  docs/source/api.rst
  test_infra/poetry.lock
  test_infra/pyproject.toml
  tests/conftest.py
  tests/unit/test_dynamodb.py
  tests/unit/test_moto.py
  tutorials/028 - DynamoDB.ipynb
Labels: enhancement, major release, breaking change

#1861 (feat) glue data quality
  awswrangler/__init__.py
  awswrangler/data_quality/__init__.py
  awswrangler/data_quality/_create.py
  awswrangler/data_quality/_get.py
  awswrangler/data_quality/_utils.py
  awswrangler/exceptions.py
  docs/source/api.rst
  test_infra/stacks/base_stack.py
  tests/conftest.py
  tests/test_data_quality.py
  tutorials/034 - Glue Data Quality.ipynb
Labels: feature

#1878 (enhancement) Minor - wr.redshift.copy - pass through commit_transaction
  awswrangler/redshift.py
Labels: enhancement

#1879 (fix) Minor - KeyError in wr.opensearch.seach && cleanup tests
  awswrangler/opensearch/_read.py
  tests/test_opensearch.py
Labels: bug

#1904 Deps: Update wheel 0.37.1 -> 0.38.1
  poetry.lock
  pyproject.toml
Labels: dependencies

#1877 feat: add read_items to dynamodb module
  awswrangler/dynamodb/__init__.py
  awswrangler/dynamodb/_read.py
  docs/source/api.rst
  tests/conftest.py
  tests/test_dynamodb.py
Labels: feature
