Repository aws/aws-sdk-pandas, pull requests merged in 2022-10, with the labels that each got.

#1653 (feat) Add partitioning on block level
  awswrangler/s3/_write_dataset.py
Labels: feature

#1646 (refactor): Make room for additional distributed engines
  .bumpversion.cfg
  .github/workflows/static-checking.yml
  CONTRIBUTING.md
  awswrangler/__init__.py
  awswrangler/_config.py
  awswrangler/_threading.py
  awswrangler/_utils.py
  awswrangler/distributed/__init__.py
  awswrangler/distributed/_distributed.py
  awswrangler/distributed/_distributed.pyi
  awswrangler/distributed/ray/__init__.py
  awswrangler/distributed/ray/_pool.py
  awswrangler/distributed/ray/_utils.py
  awswrangler/distributed/ray/datasources/__init__.py
  awswrangler/distributed/ray/datasources/pandas_text_datasource.py
  awswrangler/distributed/ray/datasources/parquet_datasource.py
  awswrangler/s3/__init__.py
  awswrangler/s3/_read_parquet.py
  awswrangler/s3/_read_text.py
  awswrangler/s3/_wait.py
  awswrangler/s3/_write.py
  awswrangler/s3/_write_dataset.py
  awswrangler/s3/_write_parquet.py
  awswrangler/s3/_write_text.py
  poetry.lock
  pyproject.toml
  tests/unit/test_s3_select.py
  tests/unit/test_s3_text.py
  tox.ini
  tutorials/034 - Distributing Calls on Ray Remote Cluster.ipynb
Labels: enhancement, Major Release, dependencies

#1631 distributed s3 write text
  awswrangler/distributed/ray/datasources/pandas_text_datasource.py
  awswrangler/distributed/ray/datasources/parquet_datasource.py
  awswrangler/s3/__init__.py
  awswrangler/s3/_read_text.py
  awswrangler/s3/_write_dataset.py
  awswrangler/s3/_write_text.py
  tests/_utils.py
  tests/load/test_s3.py
  tests/unit/test_lakeformation.py
  tests/unit/test_s3_text.py
  tests/unit/test_s3_text_compressed.py
Labels: feature

#1661 Adding "Introduction to Ray" Tutorial
  .bumpversion.cfg
  README.md
  tutorials/034 - Distributing Calls using Ray.ipynb
  tutorials/035 - Distributing Calls on Ray Remote Cluster.ipynb
Labels: documentation

#1663 regenerate poetry.lock with no update
  poetry.lock
Labels: dependencies

#1673 [skip-ci] remove semicolon from python code eol in s3 tutorial
  tutorials/003 - Amazon S3.ipynb
Labels: documentation

#1664 Improve bucketing series generation by casting only the required columns
  awswrangler/s3/_write_dataset.py
Labels: enhancement

#1674 [skip-ci] consistent kernel for jupyter notebooks
  tutorials/001 - Introduction.ipynb
  tutorials/002 - Sessions.ipynb
  tutorials/003 - Amazon S3.ipynb
  tutorials/004 - Parquet Datasets.ipynb
  tutorials/005 - Glue Catalog.ipynb
  tutorials/006 - Amazon Athena.ipynb
  tutorials/007 - Redshift, MySQL, PostgreSQL, SQL Server, Oracle.ipynb
  tutorials/008 - Redshift - Copy & Unload.ipynb
  tutorials/009 - Redshift - Append, Overwrite, Upsert.ipynb
  tutorials/010 - Parquet Crawler.ipynb
  tutorials/011 - CSV Datasets.ipynb
  tutorials/012 - CSV Crawler.ipynb
  tutorials/013 - Merging Datasets on S3.ipynb
  tutorials/014 - Schema Evolution.ipynb
  tutorials/015 - EMR.ipynb
  tutorials/016 - EMR & Docker.ipynb
  tutorials/017 - Partition Projection.ipynb
  tutorials/018 - QuickSight.ipynb
  tutorials/019 - Athena Cache.ipynb
  tutorials/020 - Spark Table Interoperability.ipynb
  tutorials/021 - Global Configurations.ipynb
  tutorials/022 - Writing Partitions Concurrently.ipynb
  tutorials/023 - Flexible Partitions Filter.ipynb
  tutorials/024 - Athena Query Metadata.ipynb
  tutorials/025 - Redshift - Loading Parquet files with Spectrum.ipynb
  tutorials/026 - Amazon Timestream.ipynb
  tutorials/027 - Amazon Timestream 2.ipynb
  tutorials/028 - DynamoDB.ipynb
  tutorials/029 - S3 Select.ipynb
  tutorials/030 - Data Api.ipynb
  tutorials/031 - OpenSearch.ipynb
  tutorials/032 - Lake Formation Governed Tables.ipynb
  tutorials/033 - Amazon Neptune.ipynb
Labels: documentation

#1677 upgrading poetry installed in workflow
  .github/workflows/cfn-nag.yml
  .github/workflows/minimal-tests.yml
  .github/workflows/static-checking.yml
  poetry.lock
  pyproject.toml
  tox.ini
Labels: dependencies

#1666 (refactor): Enable new engines with custom dispatching and other constructs
  awswrangler/__init__.py
  awswrangler/_config.py
  awswrangler/_distributed.py
  awswrangler/_threading.py
  awswrangler/_utils.py
  awswrangler/distributed/__init__.py
  awswrangler/distributed/ray/__init__.py
  awswrangler/distributed/ray/_core.py
  awswrangler/distributed/ray/_core.pyi
  awswrangler/distributed/ray/_register.py
  awswrangler/distributed/ray/modin/__init__.py
  awswrangler/distributed/ray/modin/_core.py
  awswrangler/distributed/ray/modin/_utils.py
  awswrangler/distributed/ray/modin/s3/__init__.py
  awswrangler/distributed/ray/modin/s3/_read_parquet.py
  awswrangler/distributed/ray/modin/s3/_read_text.py
  awswrangler/distributed/ray/modin/s3/_write_dataset.py
  awswrangler/distributed/ray/modin/s3/_write_parquet.py
  awswrangler/distributed/ray/modin/s3/_write_text.py
  awswrangler/lakeformation/_read.py
  awswrangler/oracle.py
  awswrangler/s3/__init__.py
  awswrangler/s3/_delete.py
  awswrangler/s3/_read_parquet.py
  awswrangler/s3/_read_text.py
  awswrangler/s3/_select.py
  awswrangler/s3/_wait.py
  awswrangler/s3/_write.py
  awswrangler/s3/_write_dataset.py
  awswrangler/s3/_write_parquet.py
  awswrangler/s3/_write_text.py
  tests/_utils.py
  tests/unit/test_distributed.py
  tests/unit/test_lakeformation.py
  tests/unit/test_s3_select.py
  tests/unit/test_s3_text.py
  tests/unit/test_s3_text_compressed.py
  tutorials/034 - Distributing Calls using Ray.ipynb
  tutorials/035 - Distributing Calls on Ray Remote Cluster.ipynb
Labels: major release, refactoring

#1686 (enhancement): Move RayLogger out of non-distributed modules
  awswrangler/_config.py
  awswrangler/distributed/ray/__init__.py
  awswrangler/distributed/ray/_core.py
  awswrangler/distributed/ray/_core.pyi
  awswrangler/distributed/ray/_register.py
  awswrangler/lakeformation/_read.py
  awswrangler/s3/_delete.py
  awswrangler/s3/_read_parquet.py
  awswrangler/s3/_select.py
  awswrangler/s3/_wait.py
Labels: enhancement, major release

#1692 (perf): Distribute data types inference
  awswrangler/_data_types.py
  awswrangler/distributed/ray/_core.py
  awswrangler/distributed/ray/_core.pyi
  awswrangler/distributed/ray/_register.py
  awswrangler/distributed/ray/modin/_data_types.py
  awswrangler/s3/_select.py
Labels: enhancement, major release, performance

#1695 (fix) partition block overwriting
  awswrangler/distributed/ray/modin/s3/_write_dataset.py
  tests/load/test_s3.py
Labels: bug

#1694 (minor) correct a few typos in our ipynb tutorials
  tutorials/006 - Amazon Athena.ipynb
  tutorials/007 - Redshift, MySQL, PostgreSQL, SQL Server, Oracle.ipynb
  tutorials/014 - Schema Evolution.ipynb
  tutorials/015 - EMR.ipynb
  tutorials/016 - EMR & Docker.ipynb
  tutorials/017 - Partition Projection.ipynb
  tutorials/018 - QuickSight.ipynb
  tutorials/019 - Athena Cache.ipynb
  tutorials/020 - Spark Table Interoperability.ipynb
  tutorials/022 - Writing Partitions Concurrently.ipynb
  tutorials/025 - Redshift - Loading Parquet files with Spectrum.ipynb
  tutorials/026 - Amazon Timestream.ipynb
  tutorials/027 - Amazon Timestream 2.ipynb
  tutorials/033 - Amazon Neptune.ipynb
Labels: documentation

#1699 Optimize distributed CSV I/O by adding PyArrow-based datasource
  awswrangler/distributed/ray/datasources/__init__.py
  awswrangler/distributed/ray/datasources/arrow_csv_datasource.py
  awswrangler/distributed/ray/modin/_utils.py
  awswrangler/distributed/ray/modin/s3/_read_text.py
  awswrangler/distributed/ray/modin/s3/_write_text.py
  tests/load/test_s3.py
Labels: performance

#1688 Dependency: Pandas Version
  poetry.lock
  pyproject.toml
Labels: dependencies

#1697 (docs): Improve documentation on running SDK for pandas at scale
  README.md
  docs/source/about.rst
  docs/source/install.rst
  tutorials/034 - Distributing Calls using Ray.ipynb
  tutorials/035 - Distributing Calls on Ray Remote Cluster.ipynb
Labels: documentation, major release

#1700 (feat) validate partitions along row axis, add warning
  awswrangler/distributed/ray/modin/_core.py
Labels: feature

#1711 (feat) distrib parquet - add missing features, enable all tests
  awswrangler/_arrow.py
  awswrangler/distributed/ray/datasources/pandas_file_based_datasource.py
  awswrangler/distributed/ray/datasources/parquet_datasource.py
  awswrangler/distributed/ray/modin/s3/_read_parquet.py
  awswrangler/distributed/ray/modin/s3/_write_parquet.py
  awswrangler/s3/_write_parquet.py
  tests/_utils.py
  tests/unit/test_s3_parquet.py
Labels: major release, feature

#1715 (perf): Distribute timestream write with executor
  README.md
  awswrangler/_data_types.py
  awswrangler/_utils.py
  awswrangler/distributed/ray/_register.py
  awswrangler/distributed/ray/modin/_utils.py
  awswrangler/timestream.py
  tests/load/test_database.py
  tests/unit/test_timestream.py
Labels: major release, feature, refactoring

#1725 Prepare pre-release 3.0.0rc1
  .bumpversion.cfg
  CONTRIBUTING.md
  CONTRIBUTING_COMMON_ERRORS.md
  README.md
  VERSION
  awswrangler/__metadata__.py
  awswrangler/athena/_read.py
  awswrangler/s3/_read_parquet.py
  awswrangler/s3/_read_text.py
  awswrangler/s3/_write_parquet.py
  awswrangler/s3/_write_text.py
  docs/source/about.rst
  docs/source/install.rst
  docs/source/layers.rst
  poetry.lock
  pyproject.toml
  test_infra/pyproject.toml
  tests/unit/test_metadata.py
  tutorials/001 - Introduction.ipynb
  tutorials/007 - Redshift, MySQL, PostgreSQL, SQL Server, Oracle.ipynb
  tutorials/014 - Schema Evolution.ipynb
  tutorials/021 - Global Configurations.ipynb
  tutorials/022 - Writing Partitions Concurrently.ipynb
  tutorials/023 - Flexible Partitions Filter.ipynb
  tutorials/034 - Distributing Calls using Ray.ipynb
  tutorials/035 - Distributing Calls on Ray Remote Cluster.ipynb
Labels: minor release

#1720 Deps: Remove upper bound limit on 'python' version
  poetry.lock
  pyproject.toml
Labels: dependencies

#1716 Bug: Add correct service names for timestream boto3 clients
  awswrangler/_config.py
  awswrangler/_utils.py
  tests/test_config.py
Labels: bug
