Repository aws/aws-sdk-pandas, pull requests merged in 2023-07, with the labels that each got.

#2369 fix: remove .lower in dtype sanitize for to_parquet
  awswrangler/s3/_write.py
Labels: bug

#2372 fix: enforce use_threads=False when Limit is supplied
  awswrangler/dynamodb/_read.py
  tests/unit/test_dynamodb.py
Labels: bug

#2398 chore: Adding new entries for added opt-in regions
  docs/source/layers.rst
Labels: documentation

#2401 fix: support pyarrow schema in DynamoDB read_items #2399
  awswrangler/dynamodb/_read.py
  tests/unit/test_dynamodb.py
Labels: bug

#2403 ci: upgrade Ray to 2.6 and fix security dependabots
  awswrangler/distributed/ray/_executor.py
  awswrangler/distributed/ray/_utils.py
  awswrangler/distributed/ray/datasources/arrow_parquet_datasource.py
  awswrangler/s3/_read_deltalake.py
  poetry.lock
  pyproject.toml
  tests/unit/test_athena.py
  tests/unit/test_athena_csv.py
  tests/unit/test_athena_parquet.py
  tests/unit/test_s3_parquet.py
  tests/unit/test_s3_select.py
  tests/unit/test_s3_text.py
  tox.ini
Labels: dependencies

#2414 feat: Add Python 3.11 support
  README.md
  building/build-lambda-layers.sh
  building/lambda/build-docker-images.sh
  building/lambda/build-lambda-layer.sh
  docs/source/install.rst
  pyproject.toml
  tox.ini
Labels: enhancement, minor release
