Repository aws/aws-sdk-pandas, pull requests merged in 2023-03, with the labels that each got.

#2079 chore: Simplify logging, fix zip bundling and reorganise tutorials
  README.md
  awswrangler/distributed/ray/datasources/pandas_file_based_datasource.py
  awswrangler/distributed/ray/modin/s3/_read_text.py
  awswrangler/dynamodb/_read.py
  awswrangler/lakeformation/_read.py
  awswrangler/s3/_delete.py
  awswrangler/s3/_describe.py
  awswrangler/s3/_read_parquet.py
  awswrangler/s3/_read_text.py
  awswrangler/s3/_select.py
  awswrangler/s3/_write_parquet.py
  awswrangler/s3/_write_text.py
  building/update-glue-lib.sh
  tutorials/001 - Introduction.ipynb
  tutorials/037 - Glue Data Quality.ipynb
  tutorials/038 - OpenSearch Serverless.ipynb
Labels: major release

#2084 deps: Upgrade ray to 2.3
  awswrangler/distributed/ray/datasources/arrow_parquet_datasource.py
  poetry.lock
  pyproject.toml
Labels: dependencies

#2081 Extract `parallelism` and `bulk_read` into `ray_modin_args`
  awswrangler/s3/_read_parquet.py
  awswrangler/s3/_read_text.py
  awswrangler/typing.py
  tests/load/test_s3.py
  tests/unit/test_s3_parquet.py
Labels: refactoring

#2091 enhancement: Add timestream common attributes
  awswrangler/timestream.py
  tests/test_timestream.py
Labels: enhancement, minor release

#2134 fix: ensure lambda layers are built in release-3.0
  building/build-lambda-layers.sh
  building/lambda/Dockerfile
  building/lambda/build-lambda-layer.sh
Labels: dependencies

#2136 fix: Config not loading environment variables for config
  awswrangler/_config.py
  tests/test_config.py
Labels: bug

#2142 test: Adding the Redshift `test_to_sql_with_identity_column` unit test
  tests/test_redshift.py
Labels: testing

#2143 feat: add benchmark tests
  tests/benchmark/__init__.py
  tests/benchmark/test_glueray.py
  tests/glue_scripts/ray_read_parquet.py
  tests/glue_scripts/wrangler_blog_simple.py
  tests/glue_scripts/wrangler_read_parquet.py
Labels: major release, performance, testing

#2045 fix: allow writing files from an empty dataframe
  awswrangler/distributed/ray/modin/s3/_write_text.py
  awswrangler/s3/_write.py
  awswrangler/s3/_write_text.py
  tests/unit/test_moto.py
  tests/unit/test_s3.py
  tests/unit/test_s3_text.py
Labels: enhancement, breaking change

#2067 feat: adding additional arg for glue database `DatabaseInput`
  awswrangler/catalog/_create.py
  tests/test_catalog.py
Labels: enhancement

#2165 chore: Documentation improvements
  .github/workflows/static-checking.yml
  README.md
  awswrangler/_config.py
  awswrangler/_utils.py
  awswrangler/annotations.py
  awswrangler/athena/_read.py
  awswrangler/athena/_utils.py
  awswrangler/catalog/_create.py
  awswrangler/catalog/_get.py
  awswrangler/data_api/rds.py
  awswrangler/data_api/redshift.py
  awswrangler/distributed/ray/_utils.py
  awswrangler/distributed/ray/datasources/arrow_parquet_datasource.py
  awswrangler/distributed/ray/modin/_core.py
  awswrangler/dynamodb/_read.py
  awswrangler/lakeformation/_read.py
  awswrangler/neptune/_neptune.py
  awswrangler/neptune/_utils.py
  awswrangler/opensearch/_read.py
  awswrangler/quicksight/_create.py
  awswrangler/quicksight/_delete.py
  awswrangler/quicksight/_describe.py
  awswrangler/quicksight/_get_list.py
  awswrangler/redshift.py
  awswrangler/s3/_read_parquet.py
  awswrangler/s3/_read_text.py
  awswrangler/s3/_select.py
  awswrangler/s3/_write_parquet.py
  awswrangler/s3/_write_text.py
  awswrangler/sqlserver.py
  awswrangler/timestream.py
  building/build-docs.sh
  docs/source/conf.py
  docs/source/index.rst
  docs/source/install.rst
  docs/source/scale.rst
  tests/load/test_s3.py
  tutorials/008 - Redshift - Copy & Unload.ipynb
  tutorials/014 - Schema Evolution.ipynb
  tutorials/023 - Flexible Partitions Filter.ipynb
  tutorials/031 - OpenSearch.ipynb
  tutorials/035 - Distributing Calls on Ray Remote Cluster.ipynb
  tutorials/036 - Distributing Calls with Glue Interactive Sessions on Ray.ipynb
  validate.sh
Labels: documentation
