Repository aws/aws-sdk-pandas, pull requests merged in 2023-04, with the labels that each got.

#2167 chore: Add typeddicts to docs
  docs/source/_templates/typed-dict-template.rst
  docs/source/api.rst
Labels: documentation

#2187 chore: prepare release 3.0
  .bumpversion.cfg
  .github/workflows/bandit.yml
  .github/workflows/minimal-tests.yml
  .github/workflows/static-checking.yml
  CONTRIBUTING_COMMON_ERRORS.md
  README.md
  VERSION
  awswrangler/__metadata__.py
  awswrangler/athena/_read.py
  awswrangler/s3/_read_parquet.py
  awswrangler/s3/_read_text.py
  awswrangler/s3/_write_parquet.py
  awswrangler/s3/_write_text.py
  docs/source/about.rst
  docs/source/install.rst
  docs/source/layers.rst
  docs/source/scale.rst
  pyproject.toml
  test_infra/pyproject.toml
  tests/unit/test_metadata.py
  tutorials/001 - Introduction.ipynb
  tutorials/007 - Redshift, MySQL, PostgreSQL, SQL Server, Oracle.ipynb
  tutorials/014 - Schema Evolution.ipynb
  tutorials/021 - Global Configurations.ipynb
  tutorials/022 - Writing Partitions Concurrently.ipynb
  tutorials/023 - Flexible Partitions Filter.ipynb
  tutorials/034 - Distributing Calls using Ray.ipynb
  tutorials/035 - Distributing Calls on Ray Remote Cluster.ipynb
  tutorials/036 - Distributing Calls with Glue Interactive Sessions on Ray.ipynb
Labels: documentation, major release

#2188 fix: Modin .dt() AttributeError
  awswrangler/athena/_read.py
  tests/unit/test_athena.py
Labels: bug

#2195 fix: opensearch mapping update error
  tests/unit/test_opensearch.py
Labels: bug

#2191 chore: Add Literal typing for mode and projection_types
  awswrangler/catalog/_create.py
  awswrangler/data_quality/_create.py
  awswrangler/emr.py
  awswrangler/mysql.py
  awswrangler/oracle.py
  awswrangler/postgresql.py
  awswrangler/quicksight/_create.py
  awswrangler/redshift.py
  awswrangler/s3/_copy.py
  awswrangler/s3/_write_parquet.py
  awswrangler/s3/_write_text.py
  awswrangler/sqlserver.py
  awswrangler/typing.py
Labels: refactoring

#2215 docs: Include our ADRs in GitHub
  .adr-dir
  adr/0001-record-architecture-decisions.md
  adr/0002-handling-unsupported-arguments-in-distributed-mode.md
  adr/0003-use-typeddict-to-group-similar-parameters.md
  adr/0004-no-alter-iam-permissions.md
  adr/0005-move-dependencies-to-optional.md
  adr/0006-deprecate-s3-merge-upsert-table.md
  adr/0007-design-of-engine-and-memory-format.md
  docs/source/_ext/copy_adr.py
  docs/source/adr.rst
  docs/source/adr/.gitignore
  docs/source/conf.py
  docs/source/index.rst
  poetry.lock
  pyproject.toml
Labels: documentation

#2237 feat: Add ability to pass schema to S3 Select
  awswrangler/s3/_select.py
  tests/unit/test_s3_select.py
Labels: feature

#2228 feat: Add `s3.to_deltalake` function
  awswrangler/s3/__init__.py
  awswrangler/s3/_read_deltalake.py
  awswrangler/s3/_write_deltalake.py
  docs/source/api.rst
  tests/unit/test_s3_deltalake.py
Labels: feature
