Repository aws/aws-sdk-pandas, pull requests merged in 2023-02, with the labels that each got.

#1978 (enhancement) Add write_table_args
  awswrangler/s3/_write_parquet.py
Labels: enhancement

#1981 (feat): Distribute DynamoDB Parallel Scan
  awswrangler/_utils.py
  awswrangler/distributed/ray/_register.py
  awswrangler/dynamodb/_read.py
  awswrangler/dynamodb/_utils.py
  awswrangler/s3/_select.py
  awswrangler/timestream.py
  tests/unit/test_dynamodb.py
Labels: major release, feature

#1977 extending arrow to include python build modules
  building/lambda/build-lambda-layer.sh
Labels: enhancement, minor release

#1992 (breaking change): Move dependencies to optional
  .flake8
  .github/workflows/cfn-nag.yml
  .github/workflows/minimal-tests.yml
  .github/workflows/static-checking.yml
  .gitignore
  CONTRIBUTING.md
  README.md
  awswrangler/_utils.py
  awswrangler/data_api/_connector.py
  awswrangler/data_api/rds.py
  awswrangler/data_api/redshift.py
  awswrangler/mysql.py
  awswrangler/neptune/__init__.py
  awswrangler/neptune/_client.py
  awswrangler/neptune/_gremlin_init.py
  awswrangler/neptune/_gremlin_parser.py
  awswrangler/neptune/_neptune.py
  awswrangler/neptune/_utils.py
  awswrangler/opensearch/_read.py
  awswrangler/opensearch/_utils.py
  awswrangler/opensearch/_write.py
  awswrangler/oracle.py
  awswrangler/postgresql.py
  awswrangler/redshift.py
  awswrangler/s3/_merge_upsert_table.py
  awswrangler/s3/_read_deltalake.py
  awswrangler/s3/_read_excel.py
  awswrangler/s3/_write_excel.py
  awswrangler/sqlserver.py
  building/build-lambda-layers.sh
  building/lambda/Dockerfile
  building/lambda/build-docker-images.sh
  docs/source/conf.py
  docs/source/index.rst
  docs/source/install.rst
  fix.sh
  poetry.lock
  pyproject.toml
  tests/unit/test_athena.py
  tests/unit/test_athena_csv.py
  tests/unit/test_neptune.py
  tests/unit/test_routines.py
  tests/unit/test_s3_deltalake.py
  tests/unit/test_s3_parquet.py
  tox.ini
  tutorials/007 - Redshift, MySQL, PostgreSQL, SQL Server, Oracle.ipynb
  tutorials/008 - Redshift - Copy & Unload.ipynb
  tutorials/009 - Redshift - Append, Overwrite, Upsert.ipynb
  tutorials/025 - Redshift - Loading Parquet files with Spectrum.ipynb
  tutorials/031 - OpenSearch.ipynb
  tutorials/033 - Amazon Neptune.ipynb
  tutorials/034 - Distributing Calls using Ray.ipynb
  tutorials/035 - OpenSearch Serverless.ipynb
  validate.sh
Labels: major release, feature, dependencies, breaking change

#1995 (fix): Add uuid to athena2pyarrow mapping
  awswrangler/_data_types.py
Labels: bug, minor release

#1993 (tests) Move AOSS collection to infra
  test_infra/poetry.lock
  test_infra/pyproject.toml
  test_infra/stacks/opensearch_stack.py
  tests/test_opensearch.py
Labels: enhancement, testing

#2000 (enhancement): Replace flatten_list with itertools.chain
  awswrangler/_utils.py
  awswrangler/dynamodb/_read.py
  awswrangler/s3/_select.py
  awswrangler/timestream.py
  poetry.lock
Labels: enhancement, major release

#1997 (enhancement) Use fast file metadata provider
  awswrangler/distributed/ray/modin/s3/_read_text.py
Labels: enhancement

#2009 test-infra: replacing cfn export with ssm parameters
  test_infra/poetry.lock
  test_infra/pyproject.toml
  test_infra/stacks/base_stack.py
  test_infra/stacks/lakeformation_stack.py
Labels: enhancement, testing

#2019 Distributed: Add support for JSON PyArrow data source
  awswrangler/distributed/ray/datasources/__init__.py
  awswrangler/distributed/ray/datasources/arrow_json_datasource.py
  awswrangler/distributed/ray/modin/s3/_read_text.py
Labels: enhancement, performance

#2022 Set ray.data parallelisation to -1 by default
  awswrangler/s3/_read_parquet.py
  awswrangler/s3/_read_text.py
Labels: enhancement

#2029 fix: `poetry.lock` merge issue
  test_infra/poetry.lock
Labels: bug

#2040 fix: Add missing TIME type to pyarrow2redshift conversion method
  awswrangler/_data_types.py
Labels: bug, minor release

#2016 Extract Athena cache settings into a TypedDict & refactor Config to support dicts
  awswrangler/_config.py
  awswrangler/athena/_read.py
  awswrangler/athena/_utils.py
  awswrangler/typing.py
  tests/unit/test_athena_cache.py
  tests/unit/test_config.py
  tutorials/019 - Athena Cache.ipynb
Labels: refactoring

#2030 (feat): Add faster Pyarrow S3fs listing in distributed mode
  awswrangler/distributed/ray/_register.py
  awswrangler/distributed/ray/datasources/pandas_text_datasource.py
  awswrangler/distributed/ray/modin/s3/_read_text.py
  awswrangler/distributed/ray/s3/_list.py
  awswrangler/s3/__init__.py
  awswrangler/s3/_list.py
  awswrangler/s3/_list.pyi
  awswrangler/s3/_read.py
  awswrangler/s3/_read_parquet.py
  awswrangler/s3/_read_text.py
  awswrangler/s3/_read_text_core.py
  tests/load/test_databases.py
  tests/load/test_s3.py
  tests/load/test_s3_modin.py
  tests/unit/test_athena_parquet.py
  tests/unit/test_s3.py
Labels: major release, feature, refactoring, performance

#2054 docs: fix contributing guide
  CONTRIBUTING.md
  tests/test_fs.py
Labels: documentation

#2033 Add `bulk_read` option for reading large amounts of Parquet files quickly
  awswrangler/distributed/ray/datasources/__init__.py
  awswrangler/distributed/ray/datasources/arrow_parquet_base_datasource.py
  awswrangler/distributed/ray/datasources/arrow_parquet_datasource.py
  awswrangler/distributed/ray/modin/s3/_read_parquet.py
  awswrangler/s3/_read_parquet.py
  tests/load/test_s3.py
  tests/unit/test_s3_parquet.py
Labels: enhancement, performance

#2065 Updating EMR release version for tests and default
  awswrangler/emr.py
  tests/conftest.py
  tests/test_emr.py
  tutorials/016 - EMR & Docker.ipynb
Labels: bug, enhancement
