Repository aws/aws-sdk-pandas, pull requests merged in 2023-06, with the labels that each got.

#2310 feat: Opensearch parallel bulk
  awswrangler/opensearch/_write.py
  tests/unit/test_opensearch.py
Labels: feature

#2288 refactor: SQL formatter
  awswrangler/_sql_formatter.py
  awswrangler/lakeformation/_read.py
  tests/unit/test_sql_params_formatter.py
Labels: refactoring

#2317 feat: Timestream Add multi measure write record example
  tutorials/026 - Amazon Timestream.ipynb
Labels: documentation

#2322 feat: Iceberg `PARTITIONED BY` and additional table properties support
  awswrangler/athena/_write_iceberg.py
  tests/unit/test_athena.py
Labels: feature

#2314 feat: Apache Spark on Amazon Athena - `wr.athena.create_spark_session` & `wr.athena.run_spark_calculation`
  awswrangler/athena/__init__.py
  awswrangler/athena/_spark.py
  awswrangler/exceptions.py
  docs/source/api.rst
  test_infra/stacks/base_stack.py
  tests/unit/test_athena_spark.py
  tutorials/041 - Apache Spark on Amazon Athena.ipynb
Labels: feature

#2326 feat: Support Athena query prepared statements & Athena parameterized queries
  awswrangler/athena/__init__.py
  awswrangler/athena/_executions.py
  awswrangler/athena/_executions.pyi
  awswrangler/athena/_read.py
  awswrangler/athena/_read.pyi
  awswrangler/athena/_statements.py
  awswrangler/athena/_utils.py
  docs/source/api.rst
  tests/unit/test_athena.py
  tests/unit/test_athena_prepared.py
  tutorials/006 - Amazon Athena.ipynb
Labels: feature

#2340 chore: Lower `packaging` version requirement
  poetry.lock
  pyproject.toml
Labels: dependencies

#2338 feat: Allow Ray 2.5 & downgrade tox
  awswrangler/distributed/ray/_executor.py
  awswrangler/distributed/ray/_utils.py
  awswrangler/distributed/ray/datasources/arrow_csv_datasource.py
  awswrangler/distributed/ray/datasources/arrow_orc_datasource.py
  awswrangler/distributed/ray/datasources/arrow_parquet_base_datasource.py
  awswrangler/distributed/ray/datasources/arrow_parquet_datasource.py
  awswrangler/distributed/ray/datasources/pandas_file_based_datasource.py
  awswrangler/distributed/ray/datasources/pandas_text_datasource.py
  awswrangler/distributed/ray/modin/_utils.py
  poetry.lock
  pyproject.toml
Labels: feature

#2344 feat: Support Athena query prepared statements & Athena parameterized queries
  awswrangler/athena/__init__.py
  awswrangler/athena/_executions.py
  awswrangler/athena/_executions.pyi
  awswrangler/athena/_read.py
  awswrangler/athena/_read.pyi
  awswrangler/athena/_statements.py
  awswrangler/athena/_utils.py
  docs/source/api.rst
  tests/unit/test_athena.py
  tests/unit/test_athena_prepared.py
  tutorials/006 - Amazon Athena.ipynb
Labels: feature

#2347 test: Make minimal tests run on mac and windows
  .github/workflows/minimal-tests.yml
Labels: testing

#2366 feat: Add CleanRooms read module
  .gitignore
  awswrangler/__init__.py
  awswrangler/_utils.py
  awswrangler/cleanrooms/__init__.py
  awswrangler/cleanrooms/_read.py
  awswrangler/cleanrooms/_utils.py
  docs/source/api.rst
  poetry.lock
  pyproject.toml
  test_infra/app.py
  test_infra/poetry.lock
  test_infra/pyproject.toml
  test_infra/stacks/cleanrooms_stack.py
  tests/_utils.py
  tests/conftest.py
  tests/unit/test_cleanrooms.py
Labels: feature, minor release
