Repository aws/aws-sdk-pandas, pull requests merged in 2023-01, with the labels that each got.

#1910 Adjust load test benchmark values
  tests/load/test_databases.py
  tests/load/test_s3.py
Labels: performance

#1913 enhancement: Adding filter to quicksight `delete_all` methods
  awswrangler/quicksight/_delete.py
  tests/test_quicksight.py
Labels: enhancement

#1925 enhancement: Support optional `measure_name` in `wr.timestream.write()`
  awswrangler/timestream.py
  tests/test_timestream.py
Labels: enhancement

#1928 refactor: quicksight test resources as fixtures
  tests/conftest.py
  tests/test_quicksight.py
Labels: bug, enhancement

#1937 (test) minor - fix mock call args error on py37
  tests/test_athena.py
Labels: bug

#1922 (feat) opensearch serverless
  awswrangler/exceptions.py
  awswrangler/opensearch/__init__.py
  awswrangler/opensearch/_read.py
  awswrangler/opensearch/_utils.py
  awswrangler/opensearch/_write.py
  tests/test_opensearch.py
  tutorials/035 - OpenSearch Serverless.ipynb
Labels: feature

#1941 (enhancement) Minor - allow override ParquetWriter args
  awswrangler/s3/_write_parquet.py
Labels: enhancement

#1939 (enhancement) Minor - add EMR configurations arg
  awswrangler/emr.py
Labels: enhancement

#1930 housekeeping: fix any unnecessary `xfail`'s in tests
  .github/workflows/check-pytest-xfails.yml
  tests/test_athena.py
  tests/test_config.py
  tests/test_fs.py
  tests/test_redshift.py
Labels: workflows, testing

#1964 (Breaking Change): Use ExecuteStatement instead of Scan for DynamoDB read_partiql
  awswrangler/dynamodb/__init__.py
  awswrangler/dynamodb/_read.py
  awswrangler/dynamodb/_utils.py
  docs/source/api.rst
  tests/test_dynamodb.py
  tests/test_moto.py
  tutorials/028 - DynamoDB.ipynb
Labels: minor release, breaking change

#1976 (fix): Content Type in lowercase
  awswrangler/opensearch/_read.py
  awswrangler/opensearch/_write.py
Labels: bug, minor release
