Repository aws/aws-sdk-pandas, pull requests merged in 2023-09, with the labels that each got.

#2460 fix: replace amazon-reviews with ursa-labs public S3 bucket
  tests/glue_scripts/wrangler_blog_simple.py
  tests/load/test_databases.py
  tests/load/test_s3.py
Labels: testing

#2466 fix: Hyphenated Iceberg table names
  awswrangler/athena/_write_iceberg.py
  tests/conftest.py
  tests/unit/test_athena.py
Labels: bug

#2465 feat: Add schema evolution to `athena.to_iceberg`
  awswrangler/athena/_write_iceberg.py
  tests/unit/test_athena.py
Labels: enhancement

#2471 fix: `requests_aws4auth` not being treated as an optional dependency
  awswrangler/opensearch/_utils.py
Labels: bug

#2474 feat: Athena - add `client_request_token`
  awswrangler/athena/_cache.py
  awswrangler/athena/_executions.py
  awswrangler/athena/_read.py
  awswrangler/athena/_utils.py
  tests/unit/test_athena_cache.py
  tox.ini
Labels: feature

#2475 feat: Redshift data api - allow all auth combinations
  awswrangler/data_api/redshift.py
  tests/unit/test_data_api.py
Labels: feature
