Repository aws/aws-sdk-pandas, pull requests merged in 2023-05, with the labels that each got.

#2214 feat: add Timestream Batch Load support
  awswrangler/_config.py
  awswrangler/exceptions.py
  awswrangler/timestream.py
  awswrangler/typing.py
  docs/source/api.rst
  docs/source/scale.rst
  tests/load/conftest.py
  tests/load/test_databases.py
  tests/unit/test_timestream.py
  tutorials/027 - Amazon Timestream 2.ipynb
Labels: feature, minor release

#2233 feat: Add Iceberg insert
  awswrangler/athena/__init__.py
  awswrangler/athena/_write_iceberg.py
  docs/source/api.rst
  docs/source/scale.rst
  tests/unit/test_athena.py
  tutorials/039 - Athena Iceberg.ipynb
Labels: feature

#2245 docs: Write ADR for the switching between PyArrow and Pandas I/O functions
  adr/0008-switching-between-pyarrow-and-pandas-based-datasources-for-csv-json-i-o.md
Labels: documentation

#2250 feat: add dynamic classification emr config
  awswrangler/emr.py
  tests/unit/test_emr.py
Labels: bug, minor release

#2227 feat: Add `chunked` parameter to DynamoDB read functions
  awswrangler/dynamodb/_read.py
  awswrangler/dynamodb/_read.pyi
  awswrangler/dynamodb/_utils.py
  tests/unit/test_dynamodb.py
Labels: feature

#2229 refactor: Move Athena & S3 function overloads to pyi files
  awswrangler/athena/__init__.py
  awswrangler/athena/_executions.py
  awswrangler/athena/_executions.pyi
  awswrangler/athena/_read.py
  awswrangler/athena/_read.pyi
  awswrangler/athena/_utils.py
  awswrangler/athena/_write_iceberg.py
  awswrangler/s3/_read_parquet.py
  awswrangler/s3/_read_parquet.pyi
  awswrangler/s3/_read_text.py
  awswrangler/s3/_read_text.pyi
  tests/unit/test_athena_cache.py
  tests/unit/test_config.py
Labels: refactoring

#2246 fix: `emr.create_cluster` was not passing security configuration to internal method
  awswrangler/emr.py
  tests/unit/test_emr.py
Labels: bug

#2255 refactor: Move Redshift module to submodules & extract overloads
  awswrangler/redshift.py
  awswrangler/redshift/__init__.py
  awswrangler/redshift/_connect.py
  awswrangler/redshift/_read.py
  awswrangler/redshift/_read.pyi
  awswrangler/redshift/_utils.py
  awswrangler/redshift/_write.py
  tests/unit/test_redshift.py
Labels: refactoring

#2256 refactor: Move Timestream module to submodules & extract overloads
  awswrangler/distributed/ray/_register.py
  awswrangler/timestream/__init__.py
  awswrangler/timestream/_create.py
  awswrangler/timestream/_delete.py
  awswrangler/timestream/_list.py
  awswrangler/timestream/_read.py
  awswrangler/timestream/_read.pyi
  awswrangler/timestream/_write.py
Labels: refactoring

#2263 feat: add time unit to timestream write API
  awswrangler/timestream/_write.py
  tests/unit/test_timestream.py
Labels: enhancement, minor release

#2267 docs: Add tutorials section for the Neptune bulk load
  tutorials/033 - Amazon Neptune.ipynb
Labels: documentation

#2278 feat: Allow user groups to be passed in `allowed_to_use` and `allowed_to_manage` when creating QuickSight resources
  awswrangler/quicksight/_create.py
  awswrangler/quicksight/_utils.py
  tests/unit/test_quicksight.py
  tutorials/018 - QuickSight.ipynb
Labels: enhancement

#2284 feat: Add Timestream `UNLOAD`
  awswrangler/s3/_list.pyi
  awswrangler/timestream/__init__.py
  awswrangler/timestream/_read.py
  awswrangler/timestream/_read.pyi
  docs/source/api.rst
  docs/source/scale.rst
  tests/unit/test_timestream.py
  tutorials/026 - Amazon Timestream.ipynb
Labels: feature

#2285 feat: add engine/memory_format os env variables and delay engine initialization
  adr/0009-lazy-engine-initialization.md
  awswrangler/__init__.py
  awswrangler/_distributed.py
  awswrangler/distributed/ray/_core.py
  docs/source/api.rst
  docs/source/scale.rst
  tests/unit/test_distributed.py
Labels: feature

#2291 docs: Add page for data_api.rds.to_sql
  awswrangler/data_api/rds.py
  docs/source/api.rst
Labels: documentation

#2292 feat: Support reading with PyArrow-backed types
  awswrangler/_config.py
  awswrangler/_data_types.py
  awswrangler/_databases.py
  awswrangler/_utils.py
  awswrangler/athena/_read.py
  awswrangler/athena/_read.pyi
  awswrangler/athena/_utils.py
  awswrangler/dynamodb/_read.py
  awswrangler/dynamodb/_read.pyi
  awswrangler/lakeformation/_read.py
  awswrangler/mysql.py
  awswrangler/oracle.py
  awswrangler/pandas/__init__.py
  awswrangler/postgresql.py
  awswrangler/redshift/_read.py
  awswrangler/redshift/_read.pyi
  awswrangler/s3/_read_deltalake.py
  awswrangler/s3/_read_parquet.py
  awswrangler/s3/_read_parquet.pyi
  awswrangler/s3/_read_text.py
  awswrangler/s3/_read_text.pyi
  awswrangler/s3/_select.py
  awswrangler/sqlserver.py
  poetry.lock
  pyproject.toml
  tests/_utils.py
  tests/unit/test_pandas_pyarrow_dtype_backend.py
  tests/unit/test_s3_parquet.py
Labels: enhancement

#2299 fix: KeyError & add lock to athena cache manager
  awswrangler/athena/_cache.py
Labels: bug

#2297 feat: Support additional parameters for Neptune bulk load
  awswrangler/neptune/__init__.py
  awswrangler/neptune/_client.py
  awswrangler/neptune/_neptune.py
  awswrangler/neptune/_utils.py
Labels: enhancement

#2306 fix: Ruff formatting errors
  awswrangler/_arrow.py
  awswrangler/_data_types.py
  awswrangler/_databases.py
  awswrangler/athena/_read.py
  awswrangler/athena/_utils.py
  awswrangler/data_api/_connector.py
  awswrangler/data_api/rds.py
  awswrangler/data_api/redshift.py
  awswrangler/dynamodb/_utils.py
  awswrangler/neptune/_gremlin_parser.py
  awswrangler/neptune/_neptune.py
  awswrangler/opensearch/_write.py
  awswrangler/oracle.py
  awswrangler/s3/_read.py
  awswrangler/s3/_read_parquet.py
  awswrangler/s3/_write_dataset.py
  pyproject.toml
  validate.sh
Labels: refactoring

#2304 feat: EMR Serverless
  awswrangler/__init__.py
  awswrangler/_config.py
  awswrangler/_utils.py
  awswrangler/dynamodb/_utils.py
  awswrangler/emr_serverless.py
  awswrangler/exceptions.py
  docs/source/api.rst
  poetry.lock
  pyproject.toml
  test_infra/stacks/base_stack.py
  tests/_utils.py
  tests/conftest.py
  tests/unit/test_emr_serverless.py
  tests/unit/test_opensearch.py
  tutorials/040 - EMR Serverless.ipynb
Labels: feature

#2307 test: Add unit test for `dtype_backend` use in `read_parquet_table`
  awswrangler/s3/_read_parquet.py
  tests/unit/test_pandas_pyarrow_dtype_backend.py
Labels: enhancement

#2309 refactor: engine `register_func` to handle type checking
  awswrangler/_distributed.py
  awswrangler/distributed/ray/_core.py
  awswrangler/distributed/ray/_register.py
  awswrangler/distributed/ray/modin/s3/_read_parquet.py
  awswrangler/distributed/ray/modin/s3/_read_text.py
  awswrangler/s3/_read_parquet.py
  awswrangler/s3/_read_text.py
  awswrangler/s3/_write_parquet.py
Labels: refactoring
