Repository aws/aws-sdk-pandas, pull requests merged in 2024-02, with the labels that each got.

#2653 chore: Upgrade ruff to 0.2.0
  docs/source/conf.py
  poetry.lock
  pyproject.toml
Labels: dependencies

#2665 feat: Add `max_results` to `athena.list_query_executions`
  awswrangler/athena/_utils.py
  tests/unit/test_athena.py
Labels: enhancement

#2692 fix: deprecate Lake Formation Governed Tables (BREAKING CHANGE)
  CONTRIBUTING.md
  README.md
  awswrangler/__init__.py
  awswrangler/_config.py
  awswrangler/_utils.py
  awswrangler/athena/_utils.py
  awswrangler/catalog/_add.py
  awswrangler/catalog/_create.py
  awswrangler/catalog/_delete.py
  awswrangler/catalog/_get.py
  awswrangler/catalog/_utils.py
  awswrangler/distributed/ray/_register.py
  awswrangler/distributed/ray/modin/s3/_write_dataset.py
  awswrangler/exceptions.py
  awswrangler/lakeformation/__init__.py
  awswrangler/lakeformation/_read.py
  awswrangler/lakeformation/_utils.py
  awswrangler/s3/_write.py
  awswrangler/s3/_write_dataset.py
  awswrangler/s3/_write_orc.py
  awswrangler/s3/_write_parquet.py
  awswrangler/s3/_write_text.py
  awswrangler/typing.py
  docs/source/api.rst
  docs/source/scale.rst
  poetry.lock
  pyproject.toml
  test_infra/app.py
  test_infra/poetry.lock
  test_infra/stacks/base_stack.py
  test_infra/stacks/cleanrooms_stack.py
  test_infra/stacks/databases_stack.py
  tests/_utils.py
  tests/conftest.py
  tests/load/test_databases.py
  tests/unit/test_catalog.py
  tests/unit/test_cleanrooms.py
  tests/unit/test_config.py
  tests/unit/test_lakeformation.py
  tests/unit/test_pandas_pyarrow_dtype_backend.py
  tests/unit/test_routines.py
  tutorials/021 - Global Configurations.ipynb
  tutorials/032 - Lake Formation Governed Tables.ipynb
Labels: breaking change
