Repository aws/aws-sdk-pandas, pull requests merged in 2024-01, with the labels that each got.

#2616 feat: `to_iceberg` support for filling missing columns in the DataFrame with None
  awswrangler/athena/_write_iceberg.py
  tests/unit/test_athena.py
  tests/unit/test_athena_iceberg.py
Labels: feature

#2627 chore: adding s3_additional_kwargs to docstrings
  awswrangler/s3/_read_text.py
Labels: documentation

#2634 docs: Fix outdated hyperlinks in documentation
  awswrangler/catalog/_create.py
  awswrangler/opensearch/_write.py
  awswrangler/s3/_read_orc.py
  awswrangler/s3/_read_parquet.py
  awswrangler/s3/_write_orc.py
  tutorials/003 - Amazon S3.ipynb
  tutorials/030 - Data Api.ipynb
  tutorials/031 - OpenSearch.ipynb
  tutorials/032 - Lake Formation Governed Tables.ipynb
Labels: documentation

#2632 feat: Enable Iceberg row deletion & add `mode` parameter to `to_iceberg`
  .github/workflows/static-checking.yml
  awswrangler/athena/__init__.py
  awswrangler/athena/_write_iceberg.py
  awswrangler/distributed/ray/modin/_utils.py
  docs/source/api.rst
  docs/source/scale.rst
  tests/unit/test_athena_iceberg.py
Labels: enhancement
